<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="arm_robot">

  <!-- Properties -->
  <xacro:property name="link1_length" value="0.4"/>
  <xacro:property name="link2_length" value="0.35"/>
  <xacro:property name="link_radius" value="0.04"/>
  <xacro:property name="joint_radius" value="0.05"/>

  <!-- Materials -->
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1.0"/>
  </material>
  <material name="orange">
    <color rgba="0.9 0.5 0.1 1.0"/>
  </material>
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>

  <!-- World link (fixed) -->
  <link name="world"/>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.1"/>
      </geometry>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.1"/>
      </geometry>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="world_to_base" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Shoulder joint (rotates around Z) -->
  <link name="shoulder_link">
    <visual>
      <geometry>
        <sphere radius="${joint_radius}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${joint_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="shoulder_pan_joint" type="revolute">
    <parent link="base_link"/>
    <child link="shoulder_link"/>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
  </joint>

  <!-- Upper arm (link 1) -->
  <link name="upper_arm_link">
    <visual>
      <geometry>
        <cylinder length="${link1_length}" radius="${link_radius}"/>
      </geometry>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${link1_length}" radius="${link_radius}"/>
      </geometry>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <origin xyz="0 0 ${link1_length/2}"/>
      <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="shoulder_lift_joint" type="revolute">
    <parent link="shoulder_link"/>
    <child link="upper_arm_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="100" velocity="1.0"/>
  </joint>

  <!-- Elbow joint -->
  <link name="elbow_link">
    <visual>
      <geometry>
        <sphere radius="${joint_radius}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${joint_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0005"/>
    </inertial>
  </link>

  <joint name="elbow_joint" type="revolute">
    <parent link="upper_arm_link"/>
    <child link="elbow_link"/>
    <origin xyz="0 0 ${link1_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.5" upper="2.5" effort="100" velocity="1.0"/>
  </joint>

  <!-- Forearm (link 2) -->
  <link name="forearm_link">
    <visual>
      <geometry>
        <cylinder length="${link2_length}" radius="${link_radius * 0.8}"/>
      </geometry>
      <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${link2_length}" radius="${link_radius * 0.8}"/>
      </geometry>
      <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="1.5"/>
      <origin xyz="0 0 ${link2_length/2}"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.0005"/>
    </inertial>
  </link>

  <joint name="forearm_joint" type="fixed">
    <parent link="elbow_link"/>
    <child link="forearm_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Wrist joint -->
  <link name="wrist_link">
    <visual>
      <geometry>
        <sphere radius="${joint_radius * 0.8}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${joint_radius * 0.8}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <inertia ixx="0.0002" ixy="0" ixz="0" iyy="0.0002" iyz="0" izz="0.0002"/>
    </inertial>
  </link>

  <joint name="wrist_joint" type="revolute">
    <parent link="forearm_link"/>
    <child link="wrist_link"/>
    <origin xyz="0 0 ${link2_length}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="50" velocity="1.5"/>
  </joint>

  <!-- End effector / gripper mount -->
  <link name="ee_link">
    <visual>
      <geometry>
        <box size="0.08 0.08 0.02"/>
      </geometry>
      <origin xyz="0 0 0.01" rpy="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.08 0.08 0.02"/>
      </geometry>
      <origin xyz="0 0 0.01" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="ee_joint" type="fixed">
    <parent link="wrist_link"/>
    <child link="ee_link"/>
    <origin xyz="0 0 0.02" rpy="0 0 0"/>
  </joint>

  <!-- Camera mount -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.03 0.08 0.02"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.03 0.08 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="ee_link"/>
    <child link="camera_link"/>
    <origin xyz="0.05 0 0" rpy="0 1.57 0"/>  <!-- Camera points forward/down -->
  </joint>

  <!-- Camera optical frame (Z forward, X right, Y down - standard camera convention) -->
  <link name="camera_optical_frame"/>

  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_optical_frame"/>
    <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
  </joint>

  <!-- Gazebo camera plugin -->
  <gazebo reference="camera_link">
    <sensor type="camera" name="arm_camera">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <ros>
          <namespace>/</namespace>
        </ros>
        <camera_name>camera</camera_name>
        <frame_name>camera_optical_frame</frame_name>
      </plugin>
    </sensor>
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- ros2_control hardware interface -->
  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="shoulder_pan_joint">
      <command_interface name="position">
        <param name="min">-3.14</param>
        <param name="max">3.14</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="shoulder_lift_joint">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="elbow_joint">
      <command_interface name="position">
        <param name="min">-2.5</param>
        <param name="max">2.5</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="wrist_joint">
      <command_interface name="position">
        <param name="min">-3.14</param>
        <param name="max">3.14</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <!-- Gazebo ros2_control plugin -->
  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <parameters>$(find robot_description)/config/controllers.yaml</parameters>
    </plugin>
  </gazebo>

  <!-- Gazebo colors -->
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="shoulder_link">
    <material>Gazebo/Orange</material>
  </gazebo>
  <gazebo reference="upper_arm_link">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="elbow_link">
    <material>Gazebo/Orange</material>
  </gazebo>
  <gazebo reference="forearm_link">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="wrist_link">
    <material>Gazebo/Orange</material>
  </gazebo>
  <gazebo reference="ee_link">
    <material>Gazebo/Grey</material>
  </gazebo>

</robot>
